0 0 dataAuditErrors
396 0 psub_StampErrorFloat
397 0 psub_StampErrorMult
398 0 psub_StampErrorConnect
403 0 wel_StampErrorFloat
404 0 wel_StampErrorMult
405 0 wel_StampErrorConnect
410 0 TWEL_StampErrorFloat
411 0 TWEL_StampErrorMult
412 0 TWEL_StampErrorConnect
1798 0 malformed device ngate_sp
1799 0 malformed device pgate_sp
1800 0 malformed device hngate_sp
1801 0 malformed device hpgate_sp
1802 0 malformed device ng_sram
1803 0 malformed device pg_sram
1804 0 malformed device welres
1805 0 malformed device sndres
1806 0 malformed device spdres
1807 0 malformed device snpyr
1808 0 malformed device sppyr
1809 0 malformed device nsndres
1810 0 malformed device nspdres
1811 0 malformed device nsnpyr
1812 0 malformed device nsppyr
1813 0 malformed device bjt_v5
1814 0 malformed device bjt_v10
1815 0 malformed device dioden
1816 0 malformed device diodep
1817 0 malformed device ngate_mm
1818 0 malformed device pgate_mm
1819 0 malformed device nmos_cap
1820 0 malformed device pmos_cap
1821 0 malformed device hngate_mm
1822 0 malformed device hpgate_mm
1823 0 malformed device ngate_lvt
1824 0 malformed device pgate_lvt
1825 0 malformed device hngate_lvt
1826 0 malformed device hpgate_lvt
1827 0 malformed device ngate_zt
1828 0 malformed device hngate_zt
1829 0 malformed device ngate_bpw
1830 0 malformed device hngate_bpw
1831 0 malformed device welres_mm
1832 0 malformed device sndres_mm
1833 0 malformed device sndres_mma
1834 0 malformed device spdres_mm
1835 0 malformed device spdres_mma
1836 0 malformed device nsndres_mm
1837 0 malformed device nspdres_mm
1838 0 malformed device nsnpyr_mm
1839 0 malformed device nsppyr_mm
1840 0 malformed device hrpyres
1841 0 malformed device m1res
1842 0 malformed device m2res
1843 0 malformed device m3res
1844 0 malformed device m4res
1845 0 malformed device m5res
1846 0 malformed device m6res
1847 0 malformed device bjt_v5_mm
1848 0 malformed device bjt_v10_mm
1849 0 malformed device cmmc_mm
1850 0 malformed device dioden_mm
1851 0 malformed device diodep_mm
1852 0 malformed device ng_rf
1853 0 malformed device ng_srf
1854 0 malformed device pg_rf
1855 0 malformed device pg_srf
1856 0 malformed device hng_rf
1857 0 malformed device hng_srf
1858 0 malformed device hpg_rf
1859 0 malformed device hpg_srf
1860 0 malformed device nsnpyr_rf
1861 0 malformed device nsppyr_rf
1862 0 malformed device hrpyres_rf
1863 0 malformed device varmis_rf
1864 0 malformed device vard_rf
1865 0 malformed device cmmc_msq_rf
1866 0 malformed device rf_pad
1867 0 malformed device ind_me
2257 0 unstable device for ind_me_Device_70
2258 0 unpreserved device ind_me_Device_70
2259 0 unstable device for rf_pad_Device_69
2260 0 unpreserved device rf_pad_Device_69
2261 0 unstable device for cmmc_msq_rf_Device_68
2262 0 unpreserved device cmmc_msq_rf_Device_68
2263 0 unstable device for vard_rf_Device_67
2264 0 unpreserved device vard_rf_Device_67
2265 0 unstable device for varmis_rf_Device_66
2266 0 unpreserved device varmis_rf_Device_66
2267 0 unstable device for hrpyres_rf_Device_65
2268 0 unpreserved device hrpyres_rf_Device_65
2269 0 unstable device for nsppyr_rf_Device_64
2270 0 unpreserved device nsppyr_rf_Device_64
2271 0 unstable device for nsnpyr_rf_Device_63
2272 0 unpreserved device nsnpyr_rf_Device_63
2273 0 unstable device for hpg_srf_Device_62
2274 0 unpreserved device hpg_srf_Device_62
2275 0 unstable device for hpg_rf_Device_61
2276 0 unpreserved device hpg_rf_Device_61
2277 0 unstable device for hng_srf_Device_60
2278 0 unpreserved device hng_srf_Device_60
2279 0 unstable device for hng_rf_Device_59
2280 0 unpreserved device hng_rf_Device_59
2281 0 unstable device for pg_srf_Device_58
2282 0 unpreserved device pg_srf_Device_58
2283 0 unstable device for pg_rf_Device_57
2284 0 unpreserved device pg_rf_Device_57
2285 0 unstable device for ng_srf_Device_56
2286 0 unpreserved device ng_srf_Device_56
2287 0 unstable device for ng_rf_Device_55
2288 0 unpreserved device ng_rf_Device_55
2289 0 unstable device for diodep_mm_DIODE_54
2290 0 unpreserved device diodep_mm_DIODE_54
2291 0 unstable device for dioden_mm_DIODE_53
2292 0 unpreserved device dioden_mm_DIODE_53
2293 0 unstable device for cmmc_mm_Device_52
2294 0 unpreserved device cmmc_mm_Device_52
2295 0 unstable device for bjt_v10_mm_BJT_51
2296 0 unpreserved device bjt_v10_mm_BJT_51
2297 0 unstable device for bjt_v5_mm_BJT_50
2298 0 unpreserved device bjt_v5_mm_BJT_50
2299 0 unstable device for m6res_Device_49
2300 0 unpreserved device m6res_Device_49
2301 0 unstable device for m5res_Device_48
2302 0 unpreserved device m5res_Device_48
2303 0 unstable device for m4res_Device_47
2304 0 unpreserved device m4res_Device_47
2305 0 unstable device for m3res_Device_46
2306 0 unpreserved device m3res_Device_46
2307 0 unstable device for m2res_Device_45
2308 0 unpreserved device m2res_Device_45
2309 0 unstable device for m1res_Device_44
2310 0 unpreserved device m1res_Device_44
2311 0 unstable device for hrpyres_Device_43
2312 0 unpreserved device hrpyres_Device_43
2313 0 unstable device for nsppyr_mm_Device_42
2314 0 unpreserved device nsppyr_mm_Device_42
2315 0 unstable device for nsnpyr_mm_Device_41
2316 0 unpreserved device nsnpyr_mm_Device_41
2317 0 unstable device for nspdres_mm_Device_40
2318 0 unpreserved device nspdres_mm_Device_40
2319 0 unstable device for nsndres_mm_Device_39
2320 0 unpreserved device nsndres_mm_Device_39
2321 0 unstable device for spdres_mma_Device_38
2322 0 unpreserved device spdres_mma_Device_38
2323 0 unstable device for spdres_mm_Device_37
2324 0 unpreserved device spdres_mm_Device_37
2325 0 unstable device for sndres_mma_Device_36
2326 0 unpreserved device sndres_mma_Device_36
2327 0 unstable device for sndres_mm_Device_35
2328 0 unpreserved device sndres_mm_Device_35
2329 0 unstable device for welres_mm_Device_34
2330 0 unpreserved device welres_mm_Device_34
2331 0 unstable device for hngate_bpw_MOS_33
2332 0 unpreserved device hngate_bpw_MOS_33
2333 0 unstable device for ngate_bpw_MOS_32
2334 0 unpreserved device ngate_bpw_MOS_32
2335 0 unstable device for hngate_zt_MOS_31
2336 0 unpreserved device hngate_zt_MOS_31
2337 0 unstable device for ngate_zt_MOS_30
2338 0 unpreserved device ngate_zt_MOS_30
2339 0 unstable device for hpgate_lvt_MOS_29
2340 0 unpreserved device hpgate_lvt_MOS_29
2341 0 unstable device for hngate_lvt_MOS_28
2342 0 unpreserved device hngate_lvt_MOS_28
2343 0 unstable device for pgate_lvt_MOS_27
2344 0 unpreserved device pgate_lvt_MOS_27
2345 0 unstable device for ngate_lvt_MOS_26
2346 0 unpreserved device ngate_lvt_MOS_26
2347 0 unstable device for hpgate_mm_MOS_25
2348 0 unpreserved device hpgate_mm_MOS_25
2349 0 unstable device for hngate_mm_MOS_24
2350 0 unpreserved device hngate_mm_MOS_24
2351 0 unstable device for pmos_cap_MOS_23
2352 0 unpreserved device pmos_cap_MOS_23
2353 0 unstable device for nmos_cap_MOS_22
2354 0 unpreserved device nmos_cap_MOS_22
2355 0 unstable device for pgate_mm_MOS_21
2356 0 unpreserved device pgate_mm_MOS_21
2357 0 unstable device for ngate_mm_MOS_20
2358 0 unpreserved device ngate_mm_MOS_20
2359 0 unstable device for diodep_DIODE_19
2360 0 unpreserved device diodep_DIODE_19
2361 0 unstable device for dioden_DIODE_18
2362 0 unpreserved device dioden_DIODE_18
2363 0 unstable device for bjt_v10_BJT_17
2364 0 unpreserved device bjt_v10_BJT_17
2365 0 unstable device for bjt_v5_BJT_16
2366 0 unpreserved device bjt_v5_BJT_16
2367 0 unstable device for nsppyr_RES_15
2368 0 unpreserved device nsppyr_RES_15
2369 0 unstable device for nsnpyr_RES_14
2370 0 unpreserved device nsnpyr_RES_14
2371 0 unstable device for nspdres_RES_13
2372 0 unpreserved device nspdres_RES_13
2373 0 unstable device for nsndres_RES_12
2374 0 unpreserved device nsndres_RES_12
2375 0 unstable device for sppyr_RES_11
2376 0 unpreserved device sppyr_RES_11
2377 0 unstable device for snpyr_RES_10
2378 0 unpreserved device snpyr_RES_10
2379 0 unstable device for spdres_RES_9
2380 0 unpreserved device spdres_RES_9
2381 0 unstable device for sndres_RES_8
2382 0 unpreserved device sndres_RES_8
2383 0 unstable device for welres_RES_7
2384 0 unpreserved device welres_RES_7
2385 0 unstable device for pg_sram_MOS_6
2386 0 unpreserved device pg_sram_MOS_6
2387 0 unstable device for ng_sram_MOS_5
2388 0 unpreserved device ng_sram_MOS_5
2389 0 unstable device for hpgate_sp_MOS_4
2390 0 unpreserved device hpgate_sp_MOS_4
2391 0 unstable device for hngate_sp_MOS_3
2392 0 unpreserved device hngate_sp_MOS_3
2393 0 unstable device for pgate_sp_MOS_2
2394 0 unpreserved device pgate_sp_MOS_2
2395 0 unstable device for ngate_sp_MOS_1
2396 0 unpreserved device ngate_sp_MOS_1
