*******************************************************************************
****** NAND_Gate schematic CMOS  <vs>  NAND_Gate layout CMOS
*******************************************************************************

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(N_18_MM) MOS                                     2       2           0       0
(P_18_MM) MOS                                     2       2           0       0
(N_18_MM:SerMos2#1) MosBlk                        -       -           1       1
(P_18_MM:ParMos2#1) MosBlk                        -       -           1       1

Match Statistics
================                                  Total             Unmatched
Cell/Device                               schematic  layout   schematic  layout
(N_18_MM) MOS                                     0       0           0       0
(P_18_MM) MOS                                     0       0           0       0
(N_18_MM:SerMos2#1) MosBlk                        1       1           0       0
(P_18_MM:ParMos2#1) MosBlk                        1       1           0       0
                                             ------  ------      ------  ------
Total                                             2       2           0       0

Match Statistics for Nets                         5       5           0       0

====================================================================[NAND_Gate]
====== Unbound Pin ============================================================
===============================================================================

S A

====================================================================[NAND_Gate]
====== Summary of Errors ======================================================
===============================================================================

Schematic  Layout     Error Type
---------  ------     ----------
 1          -         Unbound Pin

